### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by SpcCw** [huntmix/securityaddon#1]
When the app is installed, notification "Background Keeper" appears. Clicking on notification results in toast error message `"The app wasn't found in the list of installed apps"`. If the app was opened and active then it is brought to foreground, otherwise nothing happens afterwards except some flicker.

Android 7, Oukitel K10000 Max.

**Comment by zalexdev** [comment]
Android 7 api error. >8 it's ok. Will be fixed

**Comment by zalexdev** [comment]
Fixed 6.1
