### ISSUE TITLE
Encryption UX

### ISSUE THREAD

**Issue by ghost** [huntmix/securityaddon#2]
Steps to reproduce:
Choose "encrypt data" -> select files →  tap "Launch"

Tried without setting password, with short password and with simple 16-digit password.

Error message appears. OK button cannot be pressed (system Back button works).

![Screenshot_20210505-205249_Security_addon](https://user-images.githubusercontent.com/36292035/117188045-2031cb80-adcc-11eb-98a5-36689065ba65.png)

**Comment by ghost** [comment]
Phone: LeEco Le2 (X526)
OS: LineageOS 17.1 (Android 10)

**Comment by ghost** [comment]
Oh, I got it.
Password must be  entered _under launch button_
Not obvious, hard to see.

**Comment by zalexdev** [comment]
Ui will be fixed, thx for issue

**Comment by zalexdev** [comment]
UI fixed (6.1)
