### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by ghalamro** [huntmix/securityaddon#8]
Hi
Thanks for the wonderful app. Here i have some ideas

1- Set specific PIN instead of wrong PIN
2- Delete without confirm and Clear apps data couldn't work at the same time. I think when you enable Delete without confirmation, Clear apps data should become unselectable.

**Comment by zalexdev** [comment]
Thanks you for ideas. Unfortunately project is closed due to financial and time problems. Feel free to make a fork and make app better! 

P.s. Specific PIN - impossible (90%, very hard)
